# this file contains env variable that'll be used by cloudflare workers

name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDBmOGVjZjUtZTc2ZS00YzMzLThlNGItMjA2MGZjZmM4MzFkIiwidGVuYW50X2lkIjoiZGEzMGViYzRmN2RhNGEyN2U1M2NjMTQ0YjRlZTlhY2UyNWY2MzRiMGJiNjVlZDg5ODlkZDljNTY3YjE2ZWUzZiIsImludGVybmFsX3NlY3JldCI6IjViYjczMTZmLTM3NzEtNDI0MC1iMTM5LWE5OTBmMTg3YTM5MyJ9.xL-q5zmgnHi162oy3BOnE4_1wRUskxR86-sPSS9Ffv8"

JWT_SECRET="KHASVDHA"


